### ISSUE TITLE
How is the MCM matrix constructed?

### ISSUE THREAD

**Issue by MiJia-ID** [biomed-AI/SPROF-GO#3]
Your thoughts on the MCM matrix are great, but our dataset may not match the MCM dimensions you have provided as we don't have as many GOterm's, so I'd like to construct my own MCM matrix, can you explain what the arrays in the matrix represent? Or can you share the steps you took to construct the MCM matrix?

**Comment by yuanqm55** [comment]
> Your thoughts on the MCM matrix are great, but our dataset may not match the MCM dimensions you have provided as we don't have as many GOterm's, so I'd like to construct my own MCM matrix, can you explain what the arrays in the matrix represent? Or can you share the steps you took to construct the MCM matrix?

As suggested in our paper, the max constraint module (MCM) in SPROF-GO adopts a K×K matrix M (e.g., https://github.com/biomed-AI/SPROF-GO/blob/main/script/utility_files/BP_CM.npz), where M_ij = 1 if the jth GO term is a subclass of the ith GOterm, and K is the number of GO terms that need to be predicted.
